diary/urls.py
from unicodedata import name
from django.urls import path
from .import views

app_name = 'diary'

urlpatterns = [
  path('', views.IndexView.as_view(), name='index'), # /diary
  path('add/', views.AddView.as_view(), name='add'), # /diary/add
  path('update/<int:pk>/', views.UpdateView.as_view(), name='update'), # diary/update/1
  path('delete/<int:pk>', views.DeleteView.as_view(), name='delete'), #diary/delete/1
  path('detail/<int:pk>', views.DetailView.as_view(), name='detail'), 
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('diary/', include('diary.urls'))
]

diary/models.py
from cgitb import text
from turtle import title
from django.db import models
from django.utils import timezone #djangoでは、datetime.nowの代わりに、timezone.nowで現在時刻を取得する


# Create your models here.
class Day(models.Model):
  title = models.CharField('タイトル', max_length=200)
  text = models.TextField('本文')
  date = models.DateTimeField('日付', default=timezone.now)

  def __str__(self):
    return self.title

diary/forms.py
from dataclasses import field
from django import forms
from .models import Day


class DayCreateForm(forms.ModelForm):

    class Meta:
        model = Day
        fields = '__all__'

diary/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.views import generic
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import DayCreateForm
from .models import Day
# Create your views here.

class IndexView(generic.ListView):
    model = Day
    paginate_by = 3

class AddView(LoginRequiredMixin, generic.CreateView):
    model = Day
    form_class = DayCreateForm
    success_url = reverse_lazy('diary:index')

class UpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Day
    form_class = DayCreateForm
    success_url = reverse_lazy('diary:index')

class DeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Day
    success_url = reverse_lazy('diary:index')

class DetailView(generic.DetailView):
    model = Day

diary/templates/diary/base.html
<!doctype html>
<html lang="ja">
  <head>
    <title>日記アプリケーション</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  </head>
  <body>
    <div class="container">
      <nav class="nav">
        <a class="nav-link" href="{% url 'diary:index' %}">一覧</a>
        {% if user.is_superuser %}
        <a class="nav-link" href="{% url 'diary:add' %}" target="_blank">追加</a>
        {% endif %}
      </nav>
      {% block content %}
      {% endblock %}
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>

diary/templates/diary/day_confirm_delete.html
{% extends 'diary/base.html' %}

{% block content %}
<form action="" method="post">
  <table class="table">
    <tr>
      <th>{{ day.title.label }}</th>
      <td>{{ day.title }}</td>
    </tr>
    <tr>
      <th>本文</th>
      <td>{{ day.text }}</td>
    </tr>
    <tr>
      <th>日付</th>
      <td>{{ day.date }}</td>
    </tr>
  </table>
  <p>こちらのデータを削除します。</p>
  <button type="submit" class="btn btn-primary">送信</button>
  {% csrf_token %} <!-- postでのデータ送信時は必ずこれをつける、データ攻撃の対策 -->
</form>
{% endblock %}

diary/templates/diary/day_detail.html
{% extends 'diary/base.html' %}

{% block content %}
<table class="table">
  <tr>
    <th>{{ day.title.label }}</th>
    <td>{{ day.title }}</td>
  </tr>
  <tr>
    <th>本文</th>
    <td>{{ day.text | linebreaksbr }}</td>
  </tr>
  <tr>
    <th>日付</th>
    <td>{{ day.date }}</td>
  </tr>
</table>
{% endblock %}

diary/templates/diary/day_form.html
{% extends 'diary/base.html' %}

{% block content %}
<p>{{ day.title }}</p>
<form action="" method="post">
  <table class="table">
    <tr>
      <th>{{ form.title.label }}</th>
      <td>{{ form.title }}</td>
    </tr>
    <tr>
      <th>本文</th>
      <td>{{ form.text }}</td>
    </tr>
    <tr>
      <th>日付</th>
      <td>{{ form.date }}</td>
    </tr>
  </table>
  <button type="submit" class="btn btn-primary">送信</button>
  {% csrf_token %} <!-- postでのデータ送信時は必ずこれをつける、データ攻撃の対策 -->
</form>
{% endblock %}

diary/templates/diary/day_list.html
{% extends 'diary/base.html' %}

{% block content %}
<h1>日記一覧</h1>
<table class="table">
  <thead>
    <tr>
      <th>タイトル</th>
      <th>日付</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    {% for day in day_list %}
    <tr>
      <td><a href="{% url 'diary:detail' day.pk %}">{{ day.title }}</a></td>
      <td>{{ day.date }}</td>
      <td>
        {% if user.is_superuser %}
        <a href="{% url 'diary:update' day.pk %}" target="_blank">更新</a>
        {% endif %}
      </td>
      <td>
        {% if user.is_superuser %}
        <a href="{% url 'diary:delete' day.pk%}" target="_blank">削除</a>
        {% endif %}
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>

{% include 'diary/page2.html' %}

{% endblock %}

diary/templates/diary/page1.html
{% if page_obj.has_previous %}
<a href="?page={{ page_obj.previous_page_number }}">前へ</a>
{% endif %}

{% if page_obj.has_next %}
<a href="?page={{ page_obj.next_page_number }}">次へ</a>
{% endif %}

diary/templates/diary/page2.html
<nav aria-label="Page navigation">
  <ul class="pagination">
 
      {% if page_obj.has_previous %}
        <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          <span aria-hidden="true">&laquo;</span>
        </a>
      </li>
      {% endif %}
    
      {% for link_page in page_obj.paginator.page_range %}
        {% if link_page == page_obj.number %}
          <li class="page-item active">
            <a class="page-link" href="?page={{ link_page }}">
              {{ link_page }}
            </a>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ link_page }}">
              {{ link_page }}
            </a>
          </li>
        {% endif %}
      {% endfor %}
    
      {% if page_obj.has_next %}
        <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
        </a>
      </li>
      {% endif %}
    
  </ul>
</nav>